
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.border.CompoundBorder;
import javax.swing.border.EmptyBorder;
import javax.swing.border.LineBorder;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author __ntnc__
 */
public class Screen extends javax.swing.JFrame {

    /**
     * Creates new form Screen
     */
    public Screen() {
        initComponents();
    }

    public JLabel getLblBlack() {
        return lblBlack;
    }

    public void setLblBlack(JLabel lblBlack) {
        this.lblBlack = lblBlack;
    }

    public JLabel getLblBlue() {
        return lblBlue;
    }

    public void setLblBlue(JLabel lblBlue) {
        this.lblBlue = lblBlue;
    }

    public JLabel getLblClear() {
        return lblClear;
    }

    public void setLblClear(JLabel lblClear) {
        this.lblClear = lblClear;
    }

    public JLabel getLblCyan() {
        return lblCyan;
    }

    public void setLblCyan(JLabel lblCyan) {
        this.lblCyan = lblCyan;
    }

    public JLabel getLblGreen() {
        return lblGreen;
    }

    public void setLblGreen(JLabel lblGreen) {
        this.lblGreen = lblGreen;
    }

    public JLabel getLblMagenta() {
        return lblMagenta;
    }

    public void setLblMagenta(JLabel lblMagenta) {
        this.lblMagenta = lblMagenta;
    }

    public JLabel getLblRed() {
        return lblRed;
    }

    public void setLblRed(JLabel lblRed) {
        this.lblRed = lblRed;
    }

    public JLabel getLblYellow() {
        return lblYellow;
    }

    public void setLblYellow(JLabel lblYellow) {
        this.lblYellow = lblYellow;
    }

    public JPanel getPanelControl() {
        return panelControl;
    }

    public void setPanelControl(JPanel panelControl) {
        this.panelControl = panelControl;
    }

    public JPanel getPanelDraw() {
        return panelDraw;
    }

    public void setPanelDraw(JPanel panelDraw) {
        this.panelDraw = panelDraw;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDraw = new javax.swing.JPanel();
        panelControl = new javax.swing.JPanel();
        lblBlack = new javax.swing.JLabel();
        lblRed = new javax.swing.JLabel();
        lblGreen = new javax.swing.JLabel();
        lblBlue = new javax.swing.JLabel();
        lblCyan = new javax.swing.JLabel();
        lblMagenta = new javax.swing.JLabel();
        lblYellow = new javax.swing.JLabel();
        lblClear = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelDraw.setBackground(new java.awt.Color(255, 255, 255));
        panelDraw.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.gray, 5));
        panelDraw.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelDrawMouseDragged(evt);
            }
        });
        panelDraw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelDrawMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelDrawMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panelDrawMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout panelDrawLayout = new javax.swing.GroupLayout(panelDraw);
        panelDraw.setLayout(panelDrawLayout);
        panelDrawLayout.setHorizontalGroup(
            panelDrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        panelDrawLayout.setVerticalGroup(
            panelDrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelControl.setBackground(java.awt.Color.gray);

        lblBlack.setBackground(new java.awt.Color(0, 0, 0));
        lblBlack.setOpaque(true);
        lblBlack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBlackMouseClicked(evt);
            }
        });

        lblRed.setBackground(java.awt.Color.red);
        lblRed.setOpaque(true);
        lblRed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRedMouseClicked(evt);
            }
        });

        lblGreen.setBackground(java.awt.Color.green);
        lblGreen.setOpaque(true);
        lblGreen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGreenMouseClicked(evt);
            }
        });

        lblBlue.setBackground(java.awt.Color.blue);
        lblBlue.setOpaque(true);
        lblBlue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBlueMouseClicked(evt);
            }
        });

        lblCyan.setBackground(java.awt.Color.cyan);
        lblCyan.setOpaque(true);
        lblCyan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCyanMouseClicked(evt);
            }
        });

        lblMagenta.setBackground(java.awt.Color.magenta);
        lblMagenta.setOpaque(true);
        lblMagenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMagentaMouseClicked(evt);
            }
        });

        lblYellow.setBackground(java.awt.Color.yellow);
        lblYellow.setOpaque(true);
        lblYellow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblYellowMouseClicked(evt);
            }
        });

        lblClear.setBackground(new java.awt.Color(255, 255, 255));
        lblClear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblClear.setText("    CLEAR");
        lblClear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblClear.setOpaque(true);
        lblClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblClearMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelControlLayout = new javax.swing.GroupLayout(panelControl);
        panelControl.setLayout(panelControlLayout);
        panelControlLayout.setHorizontalGroup(
            panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelControlLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblClear, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                    .addComponent(lblYellow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMagenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCyan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblBlue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblGreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRed, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblBlack, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5))
        );
        panelControlLayout.setVerticalGroup(
            panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelControlLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lblBlack, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(lblRed, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblGreen, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBlue, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCyan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMagenta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblYellow, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblClear, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelDraw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelControl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDraw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelControl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblBlackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBlackMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblBlackMouseClicked

    private void lblRedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRedMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblRedMouseClicked

    private void lblGreenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGreenMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblGreenMouseClicked

    private void lblBlueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBlueMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblBlueMouseClicked

    private void lblCyanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCyanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCyanMouseClicked

    private void lblMagentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMagentaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblMagentaMouseClicked

    private void lblYellowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblYellowMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblYellowMouseClicked

    private void lblClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClearMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblClearMouseClicked

    private void panelDrawMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDrawMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panelDrawMouseClicked

    private void panelDrawMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDrawMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_panelDrawMouseReleased

    private void panelDrawMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDrawMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_panelDrawMouseDragged

    private void panelDrawMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDrawMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_panelDrawMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Screen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBlack;
    private javax.swing.JLabel lblBlue;
    private javax.swing.JLabel lblClear;
    private javax.swing.JLabel lblCyan;
    private javax.swing.JLabel lblGreen;
    private javax.swing.JLabel lblMagenta;
    private javax.swing.JLabel lblRed;
    private javax.swing.JLabel lblYellow;
    private javax.swing.JPanel panelControl;
    private javax.swing.JPanel panelDraw;
    // End of variables declaration//GEN-END:variables
}
